import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from mainClasses.SGSGE import *

monApp=QtWidgets.QApplication([])

myModel=SGModel(1100,550, windowTitle="Solutré", typeOfLayout ="grid", x=5,y=5)

def constructPlateau():
    Plateau=myModel.newCellsOnGrid(8,8,"hexagonal",size=80,gap=2,name="Plateau",backGroundImage=QPixmap("./icon/solutre/fond_solutre.jpg"))
    Plateau.deleteEntity(Plateau.getEntity(1,1))
    Plateau.deleteEntity(Plateau.getEntity(2,1))
    Plateau.deleteEntity(Plateau.getEntity(3,1))
    Plateau.deleteEntity(Plateau.getEntity(4,1))
    Plateau.deleteEntity(Plateau.getEntity(5,1))
    Plateau.deleteEntity(Plateau.getEntity(8,1))
    Plateau.deleteEntity(Plateau.getEntity(1,2))
    Plateau.deleteEntity(Plateau.getEntity(2,2))
    Plateau.deleteEntity(Plateau.getEntity(3,2))
    Plateau.deleteEntity(Plateau.getEntity(8,2))
    Plateau.deleteEntity(Plateau.getEntity(1,3))
    Plateau.deleteEntity(Plateau.getEntity(2,3))
    Plateau.deleteEntity(Plateau.getEntity(1,5))
    Plateau.deleteEntity(Plateau.getEntity(1,6))
    Plateau.deleteEntity(Plateau.getEntity(7,6))
    Plateau.deleteEntity(Plateau.getEntity(8,6))
    Plateau.deleteEntity(Plateau.getEntity(1,7))
    Plateau.deleteEntity(Plateau.getEntity(2,7))
    Plateau.deleteEntity(Plateau.getEntity(6,7))
    Plateau.deleteEntity(Plateau.getEntity(7,7))
    Plateau.deleteEntity(Plateau.getEntity(8,7))
    Plateau.deleteEntity(Plateau.getEntity(1,8))
    Plateau.deleteEntity(Plateau.getEntity(2,8))
    Plateau.deleteEntity(Plateau.getEntity(4,8))
    Plateau.deleteEntity(Plateau.getEntity(5,8))
    Plateau.deleteEntity(Plateau.getEntity(6,8))
    Plateau.deleteEntity(Plateau.getEntity(7,8))
    Plateau.deleteEntity(Plateau.getEntity(8,8))
    Plateau.getEntity(3,3).setValue("zone","Naturaliste")
    Plateau.getEntity(1,4).setValue("zone","Naturaliste")
    Plateau.getEntity(2,4).setValue("zone","Naturaliste")
    Plateau.getEntity(3,4).setValue("zone","Naturaliste")
    Plateau.getEntity(2,5).setValue("zone","Naturaliste")
    Plateau.getEntity(3,5).setValue("zone","Naturaliste")
    Plateau.getEntity(4,5).setValue("zone","Naturaliste")
    Plateau.getEntity(2,6).setValue("zone","Naturaliste")
    Plateau.getEntity(4,6).setValue("zone","Naturaliste")
    Plateau.getEntity(3,7).setValue("zone","Naturaliste")
    Plateau.getEntity(4,7).setValue("zone","Naturaliste")
    Plateau.getEntity(5,7).setValue("zone","Naturaliste")
    Plateau.getEntity(3,8).setValue("zone","Naturaliste")
    Plateau.getEntity(6,1).setValue("zone","Viticulteur")
    Plateau.getEntity(7,1).setValue("zone","Viticulteur")
    Plateau.getEntity(4,2).setValue("zone","Viticulteur")
    Plateau.getEntity(5,2).setValue("zone","Viticulteur")
    Plateau.getEntity(7,2).setValue("zone","Viticulteur")
    Plateau.getEntity(5,3).setValue("zone","Viticulteur")
    Plateau.getEntity(6,3).setValue("zone","Viticulteur")
    Plateau.getEntity(7,3).setValue("zone","Viticulteur")
    Plateau.getEntity(8,3).setValue("zone","Viticulteur")
    Plateau.getEntity(6,4).setValue("zone","Viticulteur")
    Plateau.getEntity(8,4).setValue("zone","Viticulteur")
    Plateau.getEntity(6,5).setValue("zone","Viticulteur")
    Plateau.getEntity(7,5).setValue("zone","Viticulteur")
    Plateau.getEntity(8,5).setValue("zone","Viticulteur")
    Plateau.getEntity(6,6).setValue("zone","Viticulteur")
    Plateau.getEntity(3,6).setValue("zone","Roches")
    Plateau.getEntity(6,2).setValue("zone","Roches")
    Plateau.getEntity(4,4).setValue("zone","Roches")
    Plateau.getEntity(5,4).setValue("zone","Roches")
    Plateau.getEntity(5,5).setValue("zone","Roches")
    Plateau.getEntity(4,3).setValue("zone","Village Nord")
    Plateau.getEntity(5,6).setValue("zone","Village Sud")
    Plateau.getEntity(7,4).setValue("zone","Village Est")
    Plateau.setEntities("coeurDeSite","out")
    Plateau.getEntity(5,2).setValue("coeurDeSite","in")
    Plateau.getEntity(6,2).setValue("coeurDeSite","in")
    Plateau.getEntity(5,3).setValue("coeurDeSite","in")
    Plateau.getEntity(6,3).setValue("coeurDeSite","in")
    Plateau.getEntity(7,3).setValue("coeurDeSite","in")
    Plateau.getEntity(2,4).setValue("coeurDeSite","in")
    Plateau.getEntity(3,4).setValue("coeurDeSite","in")
    Plateau.getEntity(4,4).setValue("coeurDeSite","in")
    Plateau.getEntity(5,4).setValue("coeurDeSite","in")
    Plateau.getEntity(6,4).setValue("coeurDeSite","in")
    Plateau.getEntity(3,5).setValue("coeurDeSite","in")
    Plateau.getEntity(4,5).setValue("coeurDeSite","in")
    Plateau.getEntity(5,5).setValue("coeurDeSite","in")
    Plateau.getEntity(3,6).setValue("coeurDeSite","in")
    Plateau.getEntity(4,6).setValue("coeurDeSite","in")
    return Plateau

def constructVillageNord():
    VillageNord=myModel.newCellsOnGrid(4,3,"hexagonal",size=80,gap=2,name="VillageNord",color=QColor.fromRgb(135,206,235))
    VillageNord.deleteEntity(VillageNord.getEntity(1,1))
    VillageNord.deleteEntity(VillageNord.getEntity(2,1))
    VillageNord.deleteEntity(VillageNord.getEntity(4,2))
    VillageNord.deleteEntity(VillageNord.getEntity(1,3))
    VillageNord.deleteEntity(VillageNord.getEntity(4,3))
    VillageNord.getEntity(3,1).setValue("zone","Tourisme")
    VillageNord.getEntity(4,1).setValue("zone","Elu")
    VillageNord.getEntity(3,2).setValue("zone","Elu")
    VillageNord.getEntity(3,3).setValue("zone","Elu")
    VillageNord.getEntity(1,2).setValue("zone","Habitant")
    VillageNord.getEntity(2,2).setValue("zone","Habitant")
    VillageNord.getEntity(2,3).setValue("zone","Habitant")
    return VillageNord
    
def constructVillageSud():
    VillageSud=myModel.newCellsOnGrid(4,5,"hexagonal",size=80,gap=2,name="VillageSud",color=QColor.fromRgb(176,224,230))
    VillageSud.deleteEntity(VillageSud.getEntity(1,1))
    VillageSud.deleteEntity(VillageSud.getEntity(3,1))
    VillageSud.deleteEntity(VillageSud.getEntity(4,1))
    VillageSud.deleteEntity(VillageSud.getEntity(3,2))
    VillageSud.deleteEntity(VillageSud.getEntity(4,2))
    VillageSud.deleteEntity(VillageSud.getEntity(1,3))
    VillageSud.deleteEntity(VillageSud.getEntity(4,3))
    VillageSud.deleteEntity(VillageSud.getEntity(4,4))
    VillageSud.deleteEntity(VillageSud.getEntity(1,5))
    VillageSud.deleteEntity(VillageSud.getEntity(2,5))
    VillageSud.getEntity(2,2).setValue("zone","Habitant")
    VillageSud.getEntity(2,3).setValue("zone","Habitant")
    VillageSud.getEntity(3,3).setValue("zone","Habitant")
    VillageSud.getEntity(1,4).setValue("zone","Habitant")
    VillageSud.getEntity(2,1).setValue("zone","Elu")
    VillageSud.getEntity(1,2).setValue("zone","Elu")
    VillageSud.getEntity(2,4).setValue("zone","Tourisme")
    VillageSud.getEntity(3,4).setValue("zone","Tourisme")
    VillageSud.getEntity(3,5).setValue("zone","Tourisme")
    VillageSud.getEntity(4,5).setValue("zone","Tourisme")
    return VillageSud  
    
def constructVillageEst():
    VillageEst=myModel.newCellsOnGrid(5,4,"hexagonal",size=80,gap=2,name="VillageEst",color=QColor.fromRgb(0,191,255))
    VillageEst.deleteEntity(VillageEst.getEntity(1,1))
    VillageEst.deleteEntity(VillageEst.getEntity(2,1))
    VillageEst.deleteEntity(VillageEst.getEntity(3,1))
    VillageEst.deleteEntity(VillageEst.getEntity(1,2))
    VillageEst.deleteEntity(VillageEst.getEntity(2,2))
    VillageEst.deleteEntity(VillageEst.getEntity(1,3))
    VillageEst.deleteEntity(VillageEst.getEntity(5,3))
    VillageEst.deleteEntity(VillageEst.getEntity(1,4))
    VillageEst.deleteEntity(VillageEst.getEntity(3,4))
    VillageEst.deleteEntity(VillageEst.getEntity(4,4))
    VillageEst.deleteEntity(VillageEst.getEntity(5,4))
    VillageEst.getEntity(5,1).setValue("zone","Tourisme")
    VillageEst.getEntity(4,2).setValue("zone","Tourisme")
    VillageEst.getEntity(5,2).setValue("zone","Tourisme")
    VillageEst.getEntity(4,1).setValue("zone","Elu")
    VillageEst.getEntity(3,2).setValue("zone","Habitant")
    VillageEst.getEntity(2,3).setValue("zone","Habitant")
    VillageEst.getEntity(3,3).setValue("zone","Habitant")
    VillageEst.getEntity(4,3).setValue("zone","Habitant")
    VillageEst.getEntity(2,4).setValue("zone","Habitant")
    return VillageEst
    

Plateau=constructPlateau()
VillageNord=constructVillageNord()
VillageSud=constructVillageSud()
VillageEst=constructVillageEst()



Plateau.newPov("Zones joueurs","zone",{"Roches":Qt.white,"Naturaliste":Qt.darkGreen,"Viticulteur":Qt.magenta,"Village Nord":QColor.fromRgb(135,206,235),"Village Sud":QColor.fromRgb(176,224,230),"Village Est":QColor.fromRgb(0,191,255)})
Plateau.newBorderPovColorAndWidth("Coeur de site","coeurDeSite", {"in": [Qt.red,6], "out": [Qt.black,1]})
VillageNord.newPov("Zones joueurs","zone",{"Elu":Qt.blue,"Habitant":QColor.fromRgb(255,165,0),"Tourisme":Qt.yellow})
VillageSud.newPov("Zones joueurs","zone",{"Elu":Qt.blue,"Habitant":QColor.fromRgb(255,165,0),"Tourisme":Qt.yellow})
VillageEst.newPov("Zones joueurs","zone",{"Elu":Qt.blue,"Habitant":QColor.fromRgb(255,165,0),"Tourisme":Qt.yellow})
# Legend=myModel.newLegend(grid="combined")
Legend=myModel.newLegend()

Touriste=myModel.newAgentSpecies("Touriste","circleAgent",defaultSize=40,defaultImage=QPixmap("./icon/solutre/touriste.png"))
Bouteille=myModel.newAgentSpecies("Bouteille de vin conventionnel","ellipseAgent",defaultSize=20,defaultColor=Qt.magenta)
BouteilleBio=myModel.newAgentSpecies("Bouteille de vin bio","ellipseAgent",defaultSize=20,defaultColor=Qt.green)
reserve=myModel.newCellsOnGrid(1,1,"square",size=120,gap=0,name="Réserve")
Touriste.newAgentAtCoords(reserve)
Touriste.newAgentAtCoords(reserve)
Touriste.newAgentAtCoords(reserve)
Touriste.newAgentAtCoords(reserve)

Hexagones_test=myModel.newAgentSpecies("Hexagone","hexagonAgent",{"coûtCubes":0,"couleur":None,},defaultSize=70,locationInEntity="center",defaultImage=QPixmap("./icon/solutre/N1.png"))
pioche=myModel.newCellsOnGrid(5,1,"square",size=120,gap=20,name="Pioche")
Hexagones_test.newAgentAtCoords(pioche,1,1,popupImagePath="./icon/solutre/V5.png")


Player1 = myModel.newPlayer("PlayerTest",attributesAndValues={"nbCubes":6})
Move1=myModel.newMoveAction(Hexagones_test, 'infinite')

DashBoardInd=myModel.newDashBoard("Suivi des indicateurs")
qualiteVie=myModel.newSimVariable("Qualité de vie",0)
environnement=myModel.newSimVariable("Environnement",0)
attractivite=myModel.newSimVariable("Attractivité",0)
indQualiteVie=DashBoardInd.addIndicatorOnSimVariable(qualiteVie)
indEnvironnement=DashBoardInd.addIndicatorOnSimVariable(environnement)
indAttractivite=DashBoardInd.addIndicatorOnSimVariable(attractivite)

DashBoard=myModel.newDashBoard("Suivi des services")
biodiversite=myModel.newSimVariable("Biodiversité",0)
sante=myModel.newSimVariable("Santé",0)
culture=myModel.newSimVariable("Espace culturel",0)
servicePublic=myModel.newSimVariable("Service public",0)
bar=myModel.newSimVariable("Bar",0)
restaurant=myModel.newSimVariable("Restaurant",0)
democratie=myModel.newSimVariable("Espace de démocratie",0)
loisirs=myModel.newSimVariable("Espace de loisirs",0)
emploi=myModel.newSimVariable("Emploi",0)
indSante=DashBoard.addIndicatorOnSimVariable(sante)
indCulture=DashBoard.addIndicatorOnSimVariable(culture)
indServicePublic=DashBoard.addIndicatorOnSimVariable(servicePublic)
indBar=DashBoard.addIndicatorOnSimVariable(bar)
indRestaurant=DashBoard.addIndicatorOnSimVariable(restaurant)
indDemocratie=DashBoard.addIndicatorOnSimVariable(democratie)
indLoisirs=DashBoard.addIndicatorOnSimVariable(loisirs)
indEmploi=DashBoard.addIndicatorOnSimVariable(emploi)

DashBoardRessources=myModel.newDashBoard("Ressources")
DashBoardRessources.addIndicator(Touriste,"nb")
DashBoardRessources.addIndicator(Bouteille,"nb")
DashBoardRessources.addIndicator(BouteilleBio,"nb")


myModel.launch()
# myModel.launch_withMQTT("Instantaneous")
sys.exit(monApp.exec_())